"""Add extra job  details

Revision ID: 249d6067b120
Revises: 3f936f9017d2
Create Date: 2025-08-08 23:13:24.926730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249d6067b120'
down_revision = '3f936f9017d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('experience_level', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('experience_level')
        batch_op.drop_column('job_type')

    # ### end Alembic commands ###
