"""Add extra student details and salary to jobs

Revision ID: 3a2e5b8828ae
Revises: 6d829dcf00fd
Create Date: 2025-08-08 18:51:20.987850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2e5b8828ae'
down_revision = '6d829dcf00fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_salary', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_salary', sa.Integer(), nullable=True))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('linkedin_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cgpa', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('portfolio', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('portfolio')
        batch_op.drop_column('experience')
        batch_op.drop_column('cgpa')
        batch_op.drop_column('linkedin_id')
        batch_op.drop_column('github_id')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('max_salary')
        batch_op.drop_column('min_salary')

    # ### end Alembic commands ###
